WebsiteIntranetModel/wim

modules/features/wim_page/wim_page.features.field_instance.inc, modules/features/wim_page/wim_page.strongarm.inc, themes/wim/templates/node/node--page.tpl.php
Added fields to teaser and full view modes. Added template for basic page.
=> WIM-112 - Added fields to teaser and full view modes. and template.

dev-scripts/install/install-script.sh, drupal-org.make, wim.install
=> WIM-257 - Added roles and permissions into install profile.

modules/features/wim_page/wim_page.features.field_instance.inc, modules/features/wim_page/wim_page.features.inc, modules/features/wim_page/wim_page.info, modules/features/wim_page/wim_page.module
WIM-111 - Hide tags on Basic page default view mode.	
WIM-111 - Change case in content type name.
=> Feature WIM-111

behat/features/capabilities/page/create.feature, behat/features/capabilities/page/edit.feature, wim.install
Fixed roles naming to follow drupal build in standard. Added behat test for edit page.
=> WIM-111 - Fixed roles naming and added behat test

modules/features/wim_news/wim_news.views_default.inc, themes/wim/includes/alter.inc, themes/wim/template.php
Hi @Crazylord ,
I made some changes for exposed filter, check it out and add some fixes.
Use this branch.
=> WIM-261 - Added some minor fixes for exposed filter.

behat/config/behat.yml, behat/features/capabilities/page/create.feature, docker-compose.yml
Run `docker-compose up -d` to update Docker configuration
=> Update Selenium/Behat configuration in order to support file uploads

.gitattributes
Shell scripts now will run smoothly on Windows
=> Normalize all the line endings

modules/features/wim_block_management/wim_block_management.api.php, modules/features/wim_block_management/wim_block_management.functions.inc
HTT:
It could be tested only by checking the code and files since it is related only to backend code.
Go to the project folder with Drupal code and find the wim_block_management.api.php file in profiles/wim/modules/features/wim_block_management folder. In this file you can find all available API hooks added for Felix block management functionality.
=> WIM-423 - Added hool alter for blocks management.

themes/wim/components/wim/_block--menu-top-tasks.scss, themes/wim/css/wim.css, themes/wim/dist/css/wim.css, themes/wim/js/wim.js
Hey guys,
We need to make sure that we deliver accessible components on the CI. This will save us/me a a lot of time testing and bugfixing. Try to make sure that you are at least able to use the component with a keyboard and that a user gets visual feedback when focussing on an element. I will work on some more notes/guidance for it, but also adopt this in your development proces!
@ozin7 Like discussed in Slack: Can you make a template for the <nolink> value in the menu item. So it will display like the Bootstrap dropdown anchor that is needed for accessible dropdown behaviour? See how a normal menu link is rendered and make sure that it contains all the necessary attributes. Also implement the bugfix for closing the dropdown when clicking outside of the component as Anver reported. …
=> Fixed accessibility bugs.

themes/wim/includes/theme.inc
For now alt contain only title.
=> WIM-829 - Added alt tag for menu icon item.

modules/features/wim_text_formats/wim_text_formats.module
Enable bootstrap tab for full_html
=> WIM-878 by kedramon: Enable tab button.

behat/features/capabilities/faq/overview.feature, drupal-org.make, modules/features/wim_block_management/wim_block_management.views_default.inc, modules/features/wim_core/wim_core.views_default.inc, modules/features/wim_faq/wim_faq.views_default.inc
also applied patch https://www.drupal.org/node/1793500
=> WIM-1152 by kedramon: Added plural text

behat/features/bootstrap/FeatureContext.php, behat/features/capabilities/news/create.feature, modules/features/wim_news/wim_news.features.field_instance.inc, modules/features/wim_news/wim_news.info, modules/features/wim_text_formats/wim_text_formats.linkit_profiles.inc, wim.update.inc
WIM-1245 - Changed widget type for Attachments.
WIM-1208 - Removed options from linkit, only title and alt left.
=> WIM-bugfixes

themes/wimbase/templates/node/node--agenda.tpl.php, themes/wimbase/templates/node/node--faq.tpl.php, themes/wimbase/templates/node/node--news.tpl.php, themes/wimbase/templates/node/node--page.tpl.php, themes/wimbase/templates/node/node--product.tpl.php, wim.update.inc
WIM-1244 - Removed footer tag from article tag. Added correct empty check condition.
=> WIM-1244 - double <footer>

themes/wimbase/templates/block/block--bean-editorial.tpl.php, themes/wimbase/templates/block/block--node-introduction.tpl.php
This issue needs more work. Semantics throughout the whole site should be fixed. See ticket.
=> WIM-1273 - Added names to section elements

modules/features/wim_block_management/wim_block_management.features.felix_block_set.inc, modules/features/wim_block_management/wim_block_management.info
=> WIM-1257: Add Aggregator blocks to Felix set.

modules/custom/slick_paragraphs/js/slick_paragraphs.js
=> WIM-1277: Remove pause button for single image sliders.

modules/custom/custom_lists/custom_lists.admin.inc
=> Feature/Wim-1258: Filter view modes list for List edit forms

themes/wim/components/wim/atoms/_forms.scss, themes/wim/css/wim.css, themes/wim/dist/css/wim.css, themes/wimbase/includes/preprocess.inc, themes/wimbase/templates/views/views-exposed-form.tpl.php
=> Feature/Wim-1272: Exposed filters accessibility

modules/features/wim_webform/wim_webform.module, themes/wim/components/wim/atoms/_forms.scss, themes/wim/css/wim.css, themes/wim/dist/css/wim.css
=> Feature/Wim-1265,1276: Webform components accessibility

modules/custom/wim_sss/wim_sss.theme.inc, themes/wim/components/wim/molecules/_accordion.scss, themes/wim/components/wim/templates/_block--social-links.scss, themes/wim/css/wim.css, themes/wim/dist/css/wim.css, themes/wimbase/includes/theme.inc, themes/wimbase/templates/views/views-bootstrap-accordion-plugin-style.tpl.php, wim.install
=> WIM-1241: Headings order

behat/features/capabilities/block/felix.feature, modules/features/wim_block_management/wim_block_management.api.php, modules/features/wim_block_management/wim_block_management.functions.inc
Felix is not percentage of the page but the region it is in. So changing label
=> WIM-1279 - change felix page to region

drupal-org-core.make, drupal-org.make
Update wim 2.0 core profile.
https://www.drupal.org/node/2837545
=> dr-2837545 - update core profile with module updates

modules/custom/custom_lists/custom_lists.module
This fix contain some fixes for hansel, some issues are migrated from old code, some parts are removed.
=> Fixing hansel for custom lists.

modules/features/sduconnect/sduconnect.content.inc, modules/features/sduconnect/sduconnect.delta.inc, modules/features/sduconnect/sduconnect.install
After previous refactor I missed the part of logging functionality for deleted items.
Check: WIM-642 for credentials.
=> Added logging for deleted items.

modules/features/atos_esuite/atos_esuite.import.inc
Fixing Teaser creation for atos import.
=> More intelligent teaser creation for products imported from Atos.

modules/features/atos_esuite/atos_esuite.import.inc, modules/features/atos_esuite/atos_esuite.install
Products need to be imported using filtered_html format, currently this is impossible, added variable to control this setting.
=> Added configuration for default format.

modules/features/sduconnect/sduconnect.content.inc
=> Fix summary deletion bug on import.

drupal-org.make
Added patch for Webform Clear to fix Undefined index is_new notice.
=> WIM-1336 - Fixing notice.

themes/wimbase/includes/preprocess.inc
There was an issue with culc of cols for bootstrap row, instead of block col num it set zero which is not correct.
=> Fixed bootstrap rows culc of cols.

modules/custom/xml_crawler/xml_crawler.inc, modules/custom/xml_crawler/xml_crawler.module, themes/wimbase/includes/preprocess.inc
- Added an ability to set a date token for xml sources,
- Added alter func to provide an ability to change the output of source link by other modules.
- Altered source link for CVDR xml site type.
=> WIM-1333 - Improve External Crawler (CVDR)

drupal-org.make
Felix view broke felix blocks configurations.
HTT:
1) Enable Felix views
2) Change settings for any Felix block
3) Layout will be ok, otherwise  broken.
=> Adde dpatch for Felix views module & fixed configs.

modules/custom/custom_lists/custom_lists.admin.inc, modules/custom/custom_lists/custom_lists.module
This feature include new field and allow editor to insert description metatag. Requested by Groningen.
=> Metatag field for custom lists.

wim.install, wim.update.inc
=> WIM-978 : disable user configuration for metatag

drupal-org.make
https://www.drupal.org/node/2666912
=> Added path for linkit module, updated patch for location module.

themes/wimbase/includes/theme.inc
This fixes an issue for one of the WIM customers.
=> Add accessibility attributes to dialog cloase link
